
name: Deploy

on:
  issue_comment:
    types: [created]

jobs:  
  parse:
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == 'Approved' }}
    runs-on: ubuntu-latest
    outputs:
      deploy-environment: ${{ fromJSON(steps.issue_body_parser.outputs.payload).environment }}
      ci-run-number: ${{ fromJSON(steps.issue_body_parser.outputs.payload).runNumber }}
    steps:
      - name: Comment on Issue      
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Deployment Initiated 🚀'
          
      - name: Get Issue Data
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}         
          payload_marker: target_payload 
  
  alt-deploy:
    needs: [parse]
    if: ${{ needs.parse.outputs.deploy-environment == 'alt-prod' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to ALT-PROD
        run: echo Simulating Deployment to ALT PROD
    
  deploy-prod:
    needs: [parse]
    if: ${{ needs.parse.outputs.deploy-environment == 'Prod' }}
    runs-on: ubuntu-latest    

    steps:
      - name: Deploy to PROD
        run: echo Simulating Deployment to PROD

  close-issue:
    needs: [alt-deploy, deploy-prod]
    if: ${{ always() }}
    runs-on: ubuntu-latest  
    
    steps:
      - name: Close Issue
        if: ${{ needs.alt-deploy.result == 'success' || needs.deploy-prod.result == 'success' }}
        uses: peter-evans/close-issue@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Deployment Completed 🌟'
    
    
    
    
    
    
